
name:        setoidtt
version:     0.0.1.0
license:     MIT
category:    Language
synopsis:    Implementation of a setoid type theory
author:      Andr치s Kov치cs
maintainer:  puttamalac@gmail.com
copyright:   2022 Andr치s Kov치cs
bug-reports: https://github.com/AndrasKovacs/setoidtt/issues
github:      AndrasKovacs/setoidtt

description: |
  Description TODO

flags:
  llvm:
    description: use llvm for building
    default: false
    manual : true
  dump:
    description: dump core, stg and cmm to files
    default: false
    manual: true
  debug:
    description: turn on debug info printing
    default: false
    manual: true

extra-source-files:
  - README.md

when:
  - condition: flag(dump)
    ghc-options:
      - -ddump-simpl
      - -ddump-stg-final
      - -ddump-cmm
      - -dsuppress-all
      - -dno-suppress-type-signatures
      - -ddump-to-file
  - condition: flag(llvm)
    ghc-options:
      - -fllvm

executable:
  source-dirs: src
  main: Main.hs
  dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - dynamic-array
  - flatparse
  - primdata
  - template-haskell
  - time
  - unordered-containers

  default-extensions:
  - AllowAmbiguousTypes
  - BangPatterns
  - BlockArguments
  - CPP
  - ConstraintKinds
  - DerivingVia
  - FlexibleContexts
  - ImplicitParams
  - KindSignatures
  - LambdaCase
  - MagicHash
  - MonoLocalBinds
  - PatternSynonyms
  - ScopedTypeVariables
  - Strict
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - ViewPatterns

  ghc-options:
  - -O
  - -fdicts-strict
  - -fmax-worker-args=15
  - -rtsopts
  - -threaded
  - -with-rtsopts= "-A64M -N4"
  - -Wall
  - -Wno-name-shadowing
  - -Wno-missing-signatures
  - -Wno-unused-do-bind
  - -Wno-unused-matches
  - -Wno-missing-pattern-synonym-signatures
  - -fmax-relevant-binds=0
  - -fmax-valid-hole-fits=0
