
name:        sett
version:     0.0.1.0
license:     MIT
category:    Language
synopsis:    Implementation of a setoid type theory
author:      Andr치s Kov치cs
maintainer:  puttamalac@gmail.com
copyright:   2022 Andr치s Kov치cs
bug-reports: https://github.com/AndrasKovacs/setoidtt/issues
github:      AndrasKovacs/setoidtt

description: |
  Description TODO

flags:
  llvm:
    description: use llvm for building
    default: false
    manual : true
  dump:
    description: dump core, stg and cmm to files
    default: false
    manual: true
  debug:
    description: turn on debug info printing
    default: false
    manual: true

extra-source-files:
  - README.md

when:
  - condition: flag(dump)
    ghc-options:
      - -ddump-simpl
      - -ddump-stg-final
      - -ddump-cmm
      - -dsuppress-all
      - -dno-suppress-type-signatures
      - -ddump-to-file
  - condition: flag(llvm)
    ghc-options:
      - -fllvm

default-extensions:
  - AllowAmbiguousTypes
  - BangPatterns
  - BlockArguments
  - CPP
  - ConstraintKinds
  - DataKinds
  - DerivingVia
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - ImplicitParams
  - KindSignatures
  - LambdaCase
  - MagicHash
  - MonoLocalBinds
  - MultiParamTypeClasses
  - PatternSynonyms
  - PartialTypeSignatures
  - RankNTypes
  - ScopedTypeVariables
  - Strict
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - ViewPatterns

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - bytestring
  - containers
  - dynamic-array
  - flatparse
  - ghc-prim
  - microlens-platform
  - primdata
  - strict-impl-params
  - template-haskell
  - time
  - unordered-containers
  ghc-options:
  - -O
  - -fdicts-strict
  - -fworker-wrapper-cbv
  - -fmax-worker-args=15
  - -Wall
  - -Wno-name-shadowing
  - -Wno-missing-signatures
  - -Wno-unused-do-bind
  - -Wno-unused-matches
  - -Wno-missing-pattern-synonym-signatures
  - -fmax-relevant-binds=3
  - -fmax-valid-hole-fits=0
  - -fplugin StrictImplParams

executable:
  source-dirs: exe
  main: Main.hs
  dependencies:
  - sett
  ghc-options:
  - -O
  - -rtsopts
  - -threaded
  - -with-rtsopts= "-N4 -A8M -qb0"

data-dir:
  test-data
data-files:
  - ./**/*.stt

tests:
  units:
    main: Test.hs
    source-dirs:
      - test
    dependencies:
      - dir-traverse
      - sett
      - filepath
      - bytestring
      - ansi-terminal
    ghc-options:
      - -O
      - -rtsopts
      - -threaded
      - -with-rtsopts= "-N4 -A8M -qb0"
