
resolver: nightly-2022-07-07
# compiler: ghc-9.4.1
# compiler-check: match-minor

packages:
- .

# build:
#   library-profiling: true
#   executable-profiling: true

ghc-options:
    "$everything": -split-sections

extra-deps:
- git: https://github.com/AndrasKovacs/flatparse.git
  commit: f51ead69b568f73bb7d3b47f3bc7a2b2b6db259d
- git: https://github.com/AndrasKovacs/dynamic-array.git
  commit: 043157c7b3f1715f178a932e737bb732e5e1263f
- git: https://github.com/AndrasKovacs/primdata.git
  commit: 4a7ed6b807a367a90c8dffaf1e98c3a0d0c28c32
- git: https://github.com/AndrasKovacs/ghc-strict-implicit-params.git
  commit: 215e0353374a61c0f8790371e4826b247c69580f
- dir-traverse-0.2.3.0@sha256:adcc128f201ff95131b15ffe41365dc99c50dc3fa3a910f021521dc734013bfa,2137
