
# Note: stack tracing setup:
#   1. disable strict impl params plugin in package.yaml
#   2. enable profiling here
#   3. stack clean, stack build
#   4. customize-group > haskell > haskell-interactive > stack ghci args
#      add the following args
#      --ghci-options="-fexternal-interpreter"
#      --ghci-options="-prof"
#      --ghci-options="-fprof-auto-calls"
#   5. reload ghci

resolver: lts-21.8

packages:
- .

# build:
#   library-profiling: true
#   executable-profiling: true

ghc-options:
    "$everything": -split-sections

extra-deps:
- git: https://github.com/AndrasKovacs/dynamic-array.git
  commit: a9880641ddc174db68c7e4735742e763d910453e
- git: https://github.com/AndrasKovacs/primdata.git
  commit: 46b257c41a9eb0ad99ac1cd8c5dda029601089f5
- git: https://github.com/AndrasKovacs/ghc-strict-implicit-params.git
  commit: 9097efc8860553f5d0189acc9bc56479c71c2125
- dir-traverse-0.2.3.0@sha256:adcc128f201ff95131b15ffe41365dc99c50dc3fa3a910f021521dc734013bfa,2137
